
networks:
  net-nginx:
    name: net-nginx


services:

  # данные сертификатов:
  # .local/certbot/www
  # .local/certbot/conf
  # .local/nginx/htpasswd
  nginx:
    container_name: core-nginx
    networks:
      - net-nginx
    image: nginx:1.29.1-bookworm-perl
    ports:
      - 80:80
      - 443:443
    volumes:
      - "../home/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "../home/nginx/conf:/etc/nginx/conf.d:ro"
      - "../home/nginx/.well-known:/var/www/certbot:ro"
      - "../../.local/certbot/conf:/etc/nginx/ssl:ro"
      - "../../.local/nginx/htpasswd:/etc/nginx/.htpasswd:ro"
      - type: tmpfs
        target: /var/cache/nginx
        tmpfs:
          size: 100m
          mode: 0777
    restart: always
    deploy:
      replicas: 1
    read_only: true


  # # https://github.com/hacdias/webdav
  # webdav:
  #   container_name: core-webdav
  #   hostname: webdav
  #   image: hacdias/webdav:v5.8.1
  #   volumes:
  #     - ./.wevdav-conf.yml:/config.yml:ro
  #     - /mnt/vol1/transfer-photo/wip_photo:/data/wip-photo:rw
  #     # - /mnt/vol1/transfer-photo/wip_photo:/data/wip-photo:rw
  #   ports:
  #     - 6060:8080
  #   command: -c /config.yml
  #   user: "${UID}:${GID}"
  #   deploy:
  #     restart_policy:
  #       delay: 5s
  #       condition: any
  #     replicas: 0
  #   read_only: true
