
networks:
  net-nginx:
    name: net-nginx


services:

  # данные сертификатов:
  # .local/certbot/www
  # .local/certbot/conf
  # .local/nginx/htpasswd
  nginx:
    container_name: core-nginx
    networks:
      - net-nginx
    image: nginx:1.29.1-bookworm-perl
    ports:
      - 80:80
      - 443:443
    volumes:
      - "../home/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "../home/nginx/conf:/etc/nginx/conf.d:ro"
      - "../home/nginx/.well-known:/var/www/certbot:ro"
      - "../../.local/certbot/conf:/etc/nginx/ssl:ro"
      - "../../.local/nginx/htpasswd:/etc/nginx/.htpasswd:ro"
      - type: tmpfs
        target: /var/cache/nginx
        tmpfs:
          size: 100m
          mode: 0777
    restart: always
    deploy:
      replicas: 1
    read_only: true
