#!/bin/bash

sudo apt -y update && sudo DEBIAN_FRONTEND=noninteractive apt -y install hostapd \
  dnsmasq openvpn netfilter-persistent iptables-persistent lshw vim mc iptraf-ng \
  git raspberrypi-kernel-headers build-essential dkms autossh iperf

# locale
sudo vim /etc/default/locale
```
#  File generated by update-locale
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_ALL=en_US.UTF-8
```

sudo vim /etc/environment
```
LANG=en_US.utf-8
LC_ALL=en_US.utf-8
```

sudo localedef -i en_US -f UTF-8 en_US.UTF-8

# -----------------------------------------------
# -----------------------------------------------
sudo vim /etc/dhcpcd.conf
```
interface wlan1
    static ip_address=192.168.4.1/24
    nohook wpa_supplicant
```

# check
sudo rfkill unblock wlan

# -----------------------------------------------
# -----------------------------------------------
sudo vim /etc/hostapd/hostapd.conf
```
country_code=RU
interface=wlan2
ssid=apt024
hw_mode=g
channel=7
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=121212232323343434
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
```

---------------------------

interface=wlan2
driver=nl80211
ssid=apt024

macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=121212232323343434
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP

hw_mode=a
channel=36
wmm_enabled=1

country_code=US

require_ht=1
ieee80211ac=1
require_vht=1

#This below is supposed to get us 867Mbps and works on rtl8814au doesn't work on this driver yet
#vht_oper_chwidth=1
#vht_oper_centr_freq_seg0_idx=157

ieee80211n=1
ieee80211ac=1

# -----------------------------------------------
# -----------------------------------------------
# Enable IPv4 routing
sudo vim /etc/sysctl.d/routed-ap.conf
```
net.ipv4.ip_forward=1
```
# or
/etc/sysctl.conf
uncomment #net.ipv4.ip_forward=1

# iptables
# eth0 = tap0
# ls -l /etc/iptables/
sudo iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE
sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
sudo iptables -t nat -A POSTROUTING -o gatewaytun -j MASQUERADE
sudo netfilter-persistent save

sudo iptables -t nat -D POSTROUTING 2
sudo iptables -t nat -L -v

sudo ip route add default dev wlan0 metric 50

# удалить роут для конфигурации это не требуется)
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.178.1   0.0.0.0         UG    0      0        0 eth0
0.0.0.0         160.98.123.1    0.0.0.0         UG    600    0        0 wlan0
sudo route del -net 0.0.0.0 gw 192.168.178.1 netmask 0.0.0.0 dev eth0

# -----------------------------------------------
# -----------------------------------------------
# Setup DHCP и DNS
sudo mv /etc/dnsmasq.conf /etc/dnsmasq.conf.orig
sudo vim /etc/dnsmasq.conf
```
interface=wlan1 # Listening interface
dhcp-range=192.168.4.2,192.168.4.20,255.255.255.0,24h
# Pool of IP addresses served via DHCP
domain=wlan     # Local wireless DNS domain
address=/gw.wlan/192.168.4.1 # Alias for this router
```

# -----------------------------------------------
# -----------------------------------------------
sudo vim /etc/udev/rules.d/70-persistent-net.rules
```
# built-in
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="dc:a6:32:a2:4a:54", ATTR{dev_id}=="0x0", ATTR{type}=="1", NAME="wlan0"
# egypt
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="b0:a7:b9:6a:2b:47", ATTR{dev_id}=="0x0", ATTR{type}=="1", NAME="wlan3"
# asus
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="04:42:1a:5b:95:fc", ATTR{dev_id}=="0x0", ATTR{type}=="1", NAME="wlan2"
# Realtek Semiconductor Corp. RTL8188EUS 802.11n Wireless Network Adapter
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="b4:b0:24:33:ff:d6", ATTR{dev_id}=="0x0", ATTR{type}=="1", NAME="wlan2"
```

# -----------------------------------------------
# -----------------------------------------------
# setup wi-fi
sudo vim /etc/wpa_supplicant/wpa_supplicant.conf
```
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=RU

network={
        ssid="Airtel_9108177979_5GHz"
        psk="air38663"
        key_mgmt=WPA-PSK
}

network={
        ssid="Airel_9108177979"
        psk="air38663"
        key_mgmt=WPA-PSK
}

network={
        ssid="v8_io"
        psk="55555555"
        key_mgmt=WPA-PSK
#        scan_ssid=1
#        disabled=1
}
```

# -----------------------------------------------
# -----------------------------------------------

sudo systemctl unmask hostapd
sudo systemctl enable hostapd
sudo systemctl status hostapd


# print the kernel ring buffer
dmesg
sudo ifconfig usb0 up
sudo dhclient usb0

###################################отк
# Отключить логи
systemctl status rsyslog
systemctl stop rsyslog
systemctl disable rsyslog
