PS1='\[\e[0;32m\]\u\[\e[m\] \[\e[1;34m\]\w\[\e[m\] \[\e[1;32m\]\$\[\e[m\] \[\e[1;37m\]'

source ~/_dev/environment/bash/aliases

# source ~/_dev/environment/bash/image_magick

# todo doesn`t work on mac
# PS1="\e[0;36m\u@\h \W$ \e[m"
