# Свойства роли
roles:
  - name: EXAMPLE       # Название роли
    # Разрешены входящие соединения
    allow_incoming_ssh: WORKSTATION MINI_SERVER

  - name: WORKSTATION
  - name: MINI_SERVER

  - name: PROXY_SERVER
    allow_incoming_ssh: WORKSTATION HOME_SERVER STANDBY_SERVER MINI_SERVER

  - name: HOME_SERVER
    allow_incoming_ssh: WORKSTATION

  - name: STANDBY_SERVER
    allow_incoming_ssh: HOME_SERVER WORKSTATION

# Проброс портов
port_forwarding:
  proxies: rr1 rr4 msk1 kz2 eu1

cpi:
  # Определение
  - roles: PROXY_SERVER MINI_SERVER
    host: example
    public: # Публичное подключение
      url: rr1.evgio.com
      ip: 130.255.170.133
      ipv6: ""
    local: # Локальное подключение
      url: mini.local
      ip: 192.168.1.2
      ipv6: ""
    ssh:
      port: 8080
      main:
        user: admin
        pub_key: ecdsa-sha2-nistp384
      remote:
        user:
        pub_key: ""


  - host: rr1
    roles: PROXY_SERVER
    public:
      url: rr1.evgio.com
      ip: 130.255.170.133
    local: null
    ssh:
      port: 2257
      main:
        user: adman
        pub_key: ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBHxkXrO9sNfrmnPF1Q3hDEmkxzaeXAjftsf43+mxXOPbRoXf4z4gcyNuPxuD8YCydhW+XaQBspdUoR31XB5VDIklUsVxMT31g+M0oiiWlFXuF1DdQ5ovcR/pIt5Ri3CmMg== adman@rr1

  - host: mini
    roles: MINI_SERVER
    local:
      url: mini.local
    ssh:
      main:
        user: adman
        pub_key: ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBFZL/3/5gSC5FSmOE/yW19HoY2bzzB5ejqhwwSJt85D72TgfcPc4UKyY6OfokUOXle9dq66zUytiCxeTH99AbnT7DpjGTtWDIWxUsQgzZRumJsyPVqWbJMWxoFUyT9cvWA== adman@mini
    port_forwarding:
      ports:
        - 0.0.0.0:20022::22   # ssh
        - 0.0.0.0:20443::1194 # vpn
