version: 1.0.0

# Свойства роли
roles:
  - name: EXAMPLE       # Название роли
    # Разрешены входящие ssh подключения
    allow_incoming_ssh_for_roles: WORKSTATION MINI_SERVER MINI_SERVER

  - name: WORKSTATION

  - name: MINI_SERVER
    allow_incoming_ssh_for_roles: WORKSTATION HOME_SERVER STANDBY_SERVER

  - name: PROXY_SERVER
    allow_incoming_ssh_for_roles: WORKSTATION HOME_SERVER STANDBY_SERVER MINI_SERVER

  - name: HOME_SERVER
    allow_incoming_ssh_for_roles: WORKSTATION

  - name: STANDBY_SERVER
    allow_incoming_ssh_for_roles: HOME_SERVER WORKSTATION MINI_SERVER

  - name: OFFICE_SERVER
    allow_incoming_ssh_for_roles: HOME_SERVER WORKSTATION OFFICE_SERVER


hosts:
  # Определение
  - name: example
    role: PROXY_SERVER
    description: перезагрузка в среду в 3:00
    crontab: 0 3 * * 3 /usr/bin/systemctl reboot
    public: # Публичное подключение
      url: rr1.evgio.com
      ip: 130.255.170.133
      ipv6: ""
    local: # Локальное подключение
      url: mini.local
      ip: 192.168.1.2
      ipv6: ""
    ssh:
      port: 20220
      main:
        user: admin
        pub_key: ecdsa-sha2-nistp384
      remote:
        user:
        pub_key: ""
    ssh_remote_forward:
      hosts: msk1 rr1 user4@rr4 srv5.vfstl.net
      user: remote-user
      ports:
        - 30022:0.0.0.0:22   # ssh
        - 31194:0.0.0.0:1194 # vpn - 0.0.0.0 - на все интерфейсы
        - 31194::1194        # vnc - :: для локальной сети
      connect_to:
        - remote2-user@host.site.dom -p 2022 2201::22 11941:0.0.0.0:1194
        - remote3-user@msk1 2201::22 11941:0.0.0.0:1194
        - site.com 2201::22 11941:0.0.0.0:1194
        - rr4 -p 5202 2201::22
        - remote@rr4 2201::22 11941:0.0.0.0:1194

  # ---------------------------------------------------------------------------------
  ### Proxy сервера
  # ---------------------------------------------------------------------------------
  - name: rr1
    role: PROXY_SERVER
    public:
      url: rr1.evgio.com
      ip: 130.255.170.133
    ssh:
      port: 2257
      main:
        user: adman
        pub_key: ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBHxkXrO9sNfrmnPF1Q3hDEmkxzaeXAjftsf43+mxXOPbRoXf4z4gcyNuPxuD8YCydhW+XaQBspdUoR31XB5VDIklUsVxMT31g+M0oiiWlFXuF1DdQ5ovcR/pIt5Ri3CmMg== adman@rr1


  - name: rr4
    role: PROXY_SERVER
    public:
      url: rr4.evgio.com
      ip: 185.87.51.94
    ssh:
      port: 2257
      main:
        user: adman
        pub_key: ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBHJSfDV9l7r4MljCeXNHKxPlXcqTFofVqrSn+QTZSgSjD6kLN0t91i88ZT20s20vKvR5fkYMgSDEwKZz+Lr454fmsxQVLaAeDFAbtL4gtDFfqG/6FSREyngoAD+aRqqqOg== adman@rr4


  - name: msk1
    role: PROXY_SERVER
    public:
      url: msk1.evgio.com
      ip: 195.133.46.87
    ssh:
      port: 2257
      main:
        user: adman
        pub_key: ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBI7eZR81lTDng2ibGoWsKUVPv2p5BOrgvdkPcZLceyqk1mRWOo98jH020d6G4Fwrd/peq3PL9Ergcav/Lc92LU2F09TD39sWgLhTPqJ1T5hyJXIL2MErp0p9nq5TSg28Zw== adman@msk1


  - name: kz2
    role: PROXY_SERVER
    public:
      url: kz2.evgio.com
      ip: 93.170.72.108
    ssh:
      port: 2257
      main:
        user: adman
        pub_key: ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBOXynokGGUu4Zq3GmqABFydfU1oCDyS3CYAMP0fhlzisN0K4Ovc68qWoA4DzFnpk2K0zQipp8NyP+H0WdBFLcURU3i62ygfQAVy//y1xig3SaWzweTVpeIZerA9++dNeMg== adman@kz2


  - name: eu1
    role: PROXY_SERVER
    public:
      url: eu1.evgio.com
      ip: 5.45.120.70
    ssh:
      port: 2257
      main:
        user: adman
        pub_key: ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBPpbwyFmbVB3ABe2rzyOd7Gm/oHr60swOw8B3J7pPBTsCSKjTNYcub+q4F7M44Q7Pam3VS4f0vgQkZMjduTWgvOQTWWAq/5Qv7jkNVX5tFhICFR2d3Bxas3Kj3/Vs/rkIg== adman@eu1


  # ---------------------------------------------------------------------------------
  ### Рабочие станции
  # ---------------------------------------------------------------------------------
  - name: mini
    role: MINI_SERVER
    local:
      url: mini.local
    ssh:
      main:
        user: adman
        pub_key: ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBFZL/3/5gSC5FSmOE/yW19HoY2bzzB5ejqhwwSJt85D72TgfcPc4UKyY6OfokUOXle9dq66zUytiCxeTH99AbnT7DpjGTtWDIWxUsQgzZRumJsyPVqWbJMWxoFUyT9cvWA== adman@mini
    ssh_remote_forward:
      hosts: msk1 rr1 rr4
      ports:
        - 30022:0.0.0.0:22   # ssh
        - 31194:0.0.0.0:1194 # vpn
        - 35900::5900        # vnc


  # work 16"
  - name: laptop16WorkTemp
    role: WORKSTATION
    local:
      url: jon.local
    ssh:
      main:
        user: jon
        pub_key: ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBNAvYur9yaBJ8ILDYXx70kvI5LkA7YR11DQsgQb9A2wGEhz2uKfkKwDPyaY1s3UjQnE9E1zXQu4lTS4Ggz54Xn54hpNa+ViW/YPLM+j3zpplOHkd3/9yzU8umTYXae97DA== jon@jon.local


  # work 16" the same
  - name: laptop16Work
    role: WORKSTATION
    local:
      url: inno16.local
    ssh:
      main:
        user: jon
        pub_key: ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBN6lOSYXGRyyKWrdPzau1ja7AIuFL6Rchm7LKGbe7M/VHVJVzhXIcLDNX/XQKoyMp3Aw7HRgiIrXpHow5KfoPYDsaQsC5UAa0P4v6vlxwplssSFJgjCXzUmcdZS2bWtVdg== user@inno16


  # personal 14
  - name: laptop
    role: WORKSTATION
    local:
      url: ibtv-8.local
    ssh:
      main:
        user: sem
        pub_key: ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBLlqKam9sMUGEN629GpWOpDywtwKSlCnT26lFALkrAdvskn4BBW8j6KpcV2lJ5lBXepxU6yl8W/qJlzWdwZBjmmFmrqx9vXZeWKG01g4vJPVS9aFd9XYXPMFvFe6pjOlHw== sem@ibtv-8.local


  # personal 13-2015
  - name: laptop13
    role: WORKSTATION
    local:
      url: ibtv-8.local
    ssh:
      main:
        user: sem
        pub_key: ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBJ8xEA1vYvFiJbbj960sNcLIoo790KmFWSgxxAFvvq+AcdoEQW4/Tfv0rB0/bOZ9D2jYxMLxQnaLaXyvm3VUMmk816i/+EjyOGRJxZzo4LCgDhr9p74725fZ9uh7hElmEg== evg@evg13-15.local


  # ---------------------------------------------------------------------------------
  ### Локальные сервера
  # ---------------------------------------------------------------------------------
  - name: home
    role: HOME_SERVER
    description: перезагрузка 2-а раза в мес (timezone utc +3)
    crontab:
    local:
      url: home.local core.home
      ip: 192.168.11.100
    local2:
      url: home2.local
      ip: 192.168.12.100
    ssh:
      main:
        user: adman
        pub_key: ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBGyQMkD1kkI6cti/Srn8FNX8RzjUjlKq6ynoROeXHvp9aJHqMdETId1PFiJQjfPNCNKlVVDA8lyTkn9GZtaQSi8l7NoUsPfgGvfnBVmJpy2MlnDW83QOAwUc6fDI5oM8Kg== evg@home
    ssh_remote_forward:
      hosts: rr1 rr4 msk1 kz2 eu1
      ports:
        - 2200::22            # ssh
        - 11940:0.0.0.0:1194  # openvpn
        - 10080::10080        # xeoma
        - 10090::10090        # xeoma


  - name: srv1
    role: STANDBY_SERVER
    description: перезагрузка в среду в 4:00 (timezone utc +3)
    crontab: 0 1 * * 3 /usr/bin/systemctl reboot
    local:
      url: srv1.local srv.home
      ip: 192.168.11.101
    ssh:
      main:
        user: adman
        pub_key: ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBIMVsRQ2FzF/qKVAwUwASQ2Tk1JBiCKHkphOdXYzUFmGHM5wWM8e/6UBD/zdfrz3Tgtv7M8X4wbA4cnC8TzPCY0xlklB35criLsE1L7IZRGP7ghNo9SPuRbtybIdNJQ1yg== adman@srv1
    ssh_remote_forward:
      hosts: rr1 rr4 msk1 kz2 eu1
      ports:
        - 2201::22            # ssh
        - 11941:0.0.0.0:1194  # openvpn


  - name: srv2
    role: STANDBY_SERVER
    description: перезагрузка каждую пятницу (timezone utc +3)
    crontab: 0 1 * * 5 /usr/bin/systemctl reboot
    local:
      url: srv2.local srv2.home
      ip: 192.168.11.102
    ssh:
      main:
        user: adman
        pub_key: ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBGm16LDGpzavDoaqmDwHRswdSXjCJlcSFNFPHsJONoZs6DKJaveJk4ndqrLjoUKMcCCDnkprTNSG03jwO0VQGEd/2IA8tuGIwNQW8G4dKPvxzoUiN37uhYj3w8khUIHAqA== adman@srv2
    ssh_remote_forward:
      hosts: rr1 rr4 msk1 kz2 eu1
      ports:
        - 2202::22            # ssh
        - 11942:0.0.0.0:1194  # openvpn


  # ---------------------------------------------------------------------------------
  ### Офис
  # ---------------------------------------------------------------------------------
  - name: office-server
    role: OFFICE_SERVER
    description:
    local:
      url: main.local
      ip: 192.168.1.200
    ssh:
      main:
        user: evg
        pub_key: ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBE9qsJbSRrCYARg2uPSSX0TMzCaVzuEgv09FEnlRefzB6RbpmhHkPLJ+yn6k2qWQICYKebBY8nKjFZrgOAGQx+3tp+HKRESU2yP3+RBRtLCUBvQu1ULOYp5jk3gKcIDtFg== evg@office-server
    ssh_remote_forward:
      user: forward-user
      hosts: msk1 rr1 rr4
      ports:
        - 61022:0.0.0.0:22    # ssh
        - 61194:0.0.0.0:1194  # vpn
        - 61080:0.0.0.0:10080  # cctv xeoma
        - 61090:0.0.0.0:10090  # cctv http


  - name: office-mini-tv
    role: OFFICE_SERVER
    description: перезагрузка каждую пятницу
    crontab: 0 3 * * 6 /usr/bin/systemctl reboot
    local:
      url: mini-tv.local
      ip: 192.168.1.202
    ssh:
      main:
        user: evg
        pub_key: ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBOrXJXPdUGWv1AlkELzcFv+E7fatcPhi8Wg6vB+AFvNNXOqh5YZrp4ye3xH/PiOxh5LcV7Ghfc7phLTzN7AISMFJskCsiMq7QmCBgQhKx4kJXWxBdASHDBddvdlUYNVVKg== evg@office-mini-tv
    ssh_remote_forward:
      user: forward-user
      hosts: msk1 rr1 rr4
      ports:
        - 62022:0.0.0.0:22    # ssh
        - 62194:0.0.0.0:1194  # vpn
        - 62059::5900  # vnc


  - name: office-mini-pin1
    role: OFFICE_SERVER
    description: перезагрузка каждый вторник
    crontab: 0 3 * * 3 /usr/bin/systemctl reboot
    local:
      url: mini-pin1.local
      ip: 192.168.1.204
    ssh:
      main:
        user: evg
        pub_key: ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBGqLDqDRifyckCeDIblL0vipBEPJ/ttML23l475xYI8zjYpaDOGoig8ivOckNPu4QKAke5/lvxrZ9MzSAY56U5eMTA9ARdVo+Hq0C0lZmBk3ih+t4XmVvOXSVd544iiz1Q== evg@office-mini-pin1


