set number
syntax on
set incsearch
set hlsearch
set termencoding=utf8
set nocompatible
set ruler
set showcmd
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb
set mousehide
set autoindent
" set nowrap
set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set smartindent
set showmatch
" set cursorline
highlight CursorLine guibg=lightblue ctermbg=lightgray
highlight CursorLine term=none cterm=none
set history=200
set wildmenu
" set list listchars=tab:→\ ,trail:·
filetype plugin on
set mouse-=a
