
# networks:
#   net-hq47:
#     name: net-hq47


services:
  # https://github.com/alexta69/metube
  metube:
    container_name: metube
    image: ghcr.io/alexta69/metube
    ports:
      - '8005:8081'
    volumes:
      - '/mnt/hdd2t_media/download_youtube:/downloads'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 200M
      restart_policy:
        delay: 5s
        condition: any
      replicas: 1


  minidlna: 
    container_name: minidlna 
    build:
      context: ../../docker-files
      dockerfile: minidlna.dockerfile
    image: mini47/minidlna:1.0
    volumes: 
      - ./configs/minidlna-mini47.conf:/app/minidlna.conf:ro
      - /mnt/memfs/minidlna/cache:/app/cache:rw
      - /mnt/memfs/minidlna/logs:/app/logs:rw
      
      - /mnt/media_vol/content:/media1:ro
      - /mnt/media_vol/download_youtube:/media2/download_youtube:ro 
    command:
      - sh 
      - -c 
      - |
        minidlnad -f "/app/minidlna.conf" -P "/tmp/minidlna.pid" -R -r 
        tail -f /dev/null
    # environment:
    #   - MINIDLNA_media_dir=V,/media 
    #   - MINIDLNA_friendly_name=MiniDLNA 
    #   - MINIDLNA_merge_media_dirs=yes 
    #   - MINIDLNA_force_sort_criteria= upnp:class, upnp:originalTrackNumber, dc:title 
    #   - MINIDLNA_root_container=B
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 100m
      restart_policy:
        delay: 5s
        condition: any
      replicas: 1
